# Reusable deploy template
name: Deploy template

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      concurrency:
        required: true
        type: string
    secrets:
      ENV:
        required: true

jobs:
  deploy:
    name: deploy serverless functions
    runs-on: ubuntu-latest
    environment: ${{inputs.environment}}
    concurrency: ${{inputs.concurrency}}
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: |
          node -e "console.log(\"ENV: \", process.env.ENV)"
        env:
          ENV: ${{ secrets.ENV }}
      - run: npm ci
      - run: npm run deploy
        env:
          ENV: ${{ secrets.ENV }}
