# From : https://github.com/actions/starter-workflows/blob/main/ci/node.js.yml
# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test project

on:
  create:
    tags: 'v*'

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    concurrency: production
    uses: joselucvoltaire/serverless/.github/workflows/deploy.yml@github_action