name: Deploy to staging

on:
  workflow_run:
    workflows: [Test Main]
    types: [completed]
    branches: [main]

jobs:
  deploy-to-staging:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: joselucvoltaire/serverless/.github/workflows/deploy.yml@main
    with:
      environment: staging
      concurrency: staging
