name: Deploy to staging

on:
  workflow_run:
    workflows: [Test Main]
    types: [completed]
    branches: [main]

jobs:
  deploy-to-staging:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/deploy.yml
    environment: staging
    concurrency: staging
